#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

if [ $# -ne 2 ] && [ "$1" != "ports:help" ]
then
  "$0" ports:help
  exit 1
fi

OLDIFS="$IFS"
IFS=" "
SUBCOMMAND="$1"
APP=app/"$2":latest

case "$SUBCOMMAND" in
  ports)
    INSTANCES=$(docker ps | grep "$APP" | cut -d\  -f1 | tr '\n' ' ')
    for i in $INSTANCES; do
      docker inspect "$i" | grep HostPort | cut -d\" -f4 || true 
    done | uniq
    ;;
  ports:open)
    for p in $("$0" ports "$2") ; do
      echo -n "opening $p/tcp .. ";
      sudo ufw allow "$p"/tcp > /dev/null 2>&1 && echo OK || echo ERROR;
    done
    ;;
  ports:close)
    for p in $("$0" ports "$2") ; do
      echo -n "closing $p/tcp .. ";
      sudo ufw delete allow "$p"/tcp > /dev/null 2>&1 && echo OK || echo ERROR;
    done
    ;;
  help)
   cat && cat<<EOF
Usage: $(basename "$0") SUBCOMMAND APP_NAME
Available subcommands:
ports <app>                                     show all ports belonging to <app>
ports:open <app>                                open all ports belonging to <app>
ports:close <app>                               close all ports belonging to <app>
EOF
    ;;
esac

IFS="$OLDIFS"
