#!/usr/bin/env bash
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/config"
[[ " help $PLUGIN_COMMAND_PREFIX:help " == *" $1 "* ]] || [[ "$1" == "$PLUGIN_COMMAND_PREFIX:"* ]] || exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_BASE_PATH/common/functions"
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/functions"

case "$1" in
  $PLUGIN_COMMAND_PREFIX)
    "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/subcommands/default" "$@"
    ;;

  $PLUGIN_COMMAND_PREFIX:close)
    "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/subcommands/close" "$@"
    ;;

  $PLUGIN_COMMAND_PREFIX:list)
    "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/subcommands/list" "$@"
    ;;

  $PLUGIN_COMMAND_PREFIX:open)
    "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/subcommands/open" "$@"
    fn-ports-open "$APP"
    ;;

  help | $PLUGIN_COMMAND_PREFIX:help)
    help_content_func() {
      # shellcheck disable=SC2034
      declare desc="return $PLUGIN_COMMAND_PREFIX plugin help content"
      cat<<help_content
    $PLUGIN_COMMAND_PREFIX:list <app>, show all ports belonging to the app
    $PLUGIN_COMMAND_PREFIX:open <app>, open all ports belonging to the app
    $PLUGIN_COMMAND_PREFIX:close <app>, close all ports belonging to the app
help_content
    }

    help_list_func() {
      # shellcheck disable=SC2034
      declare desc="return $PLUGIN_COMMAND_PREFIX plugin help content"
      cat<<help_list
-----> Ports available for playground
       32771
help_list
    }

    if [[ $1 = "$PLUGIN_COMMAND_PREFIX:help" ]] ; then
      echo -e "Usage: dokku $PLUGIN_COMMAND_PREFIX[:COMMAND] <app>"
      echo ''
      echo "Manage open application ports."
      echo ''
      echo 'Example:'
      echo ''
      echo "\$ dokku $PLUGIN_COMMAND_PREFIX:list"
      help_list_func
      echo ''
      echo 'Additional commands:'
      help_content_func | sort | column -c2 -t -s,
    elif [[ $(ps -o command= $PPID) == *"--all"* ]]; then
      help_content_func
    else
      cat<<help_desc
    $PLUGIN_COMMAND_PREFIX, Plugin for managing open ports
help_desc
    fi
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;
esac

IFS="$OLDIFS"
