#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_AVAILABLE_PATH/ufw/functions"

ufw-post-deploy() {
  declare APP="$1"

  if [[ "$(fn-ufw-can-expose-ports "$APP")" == "false" ]]; then
    return
  fi
  fn-ufw-open "$APP"
}

ufw-post-deploy "$@"
