#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1"; PORT="$2"

dokku ports:open "$APP"
if [[ $? != 0 ]] ; then
	echo Error opening port "$PORT" for "$APP".
	exit 1
else
	echo Opened port "$PORT" for app "$APP".
fi
