#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_AVAILABLE_PATH/ports/functions"

ports-post-deploy() {
  declare APP="$1"

  if [[ "$(fn-can-expose-ports "$APP")" == "false" ]]; then
    return
  fi
  fn-ports-open "$APP"
}

ports-post-deploy "$@"
