#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_AVAILABLE_PATH/ports/functions"

ports-pre-delete() {
  declare APP="$1"
  fn-ports-close "$APP"
}

ports-pre-delete "$@"
