#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/ufw/functions"

ufw-close-cmd() {
  declare desc="close all ports belonging to the app"
  local cmd="ufw:close"
  [[ "$1" == "$cmd" ]] && shift 1
  local APP="$1"; verify_app_name "$APP"
  fn-ufw-close "$APP"
}

ufw-close-cmd "$@"
